# Generated by Django 5.1.2 on 2024-11-05 13:55

import django.core.validators
import djmoney.models.fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_good_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='RUB', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01000000000000000020816681711721685132943093776702880859375'), message='Цена на товар не может быть отрицательной!'), django.core.validators.MaxValueValidator(Decimal('999999.98999999999068677425384521484375'))], verbose_name='Цена'),
        ),
    ]
