# Generated by Django 5.1.2 on 2024-11-05 14:22

import djmoney.models.fields
import djmoney.models.validators
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_alter_good_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='RUB', max_digits=8, validators=[djmoney.models.validators.MinMoneyValidator(limit_value=Decimal('0.01000000000000000020816681711721685132943093776702880859375'), message='Цена на товар не может быть отрицательной или равняться 0!'), djmoney.models.validators.MaxMoneyValidator(limit_value=Decimal('999999.98999999999068677425384521484375'), message='Цена на товар не может быть больше 999999.99!')], verbose_name='Цена'),
        ),
    ]
